name: Sync Loon to Surge

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests
      - run: python Surge/script/fktg.py
      - run: |
          mv  fktg Surge/ip/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Surge/ip/fktg
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto sync"
          git push
